import type { Metadata } from "next";
import { Poppins, Henny_Penny, Lilita_One } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'


import Providers from "./provider/Providers";
import Navbar from "@/components/navbar";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Footer } from "@/components/footer";

const poppins = Poppins({
  weight: ['400', '700', '200', '100', '300', '400'],
  variable: "--font-poppins",
  subsets: ["latin"],
});

const liltaOne = Lilita_One({
  weight: ["400"],
  variable: "--font-lilita-one",
  subsets: ["latin"],
});

const hennyPenny = Henny_Penny({
  weight: ["400"],
  variable: "--font-Henny-Penny",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={cn(`antialiased`, poppins.className,)}>
        <body>
          <Providers>
            <div className="min-h-screen">

              <Navbar />
              {children}
              <Footer />
            </div>
          </Providers>
        </body>
      </html>
    </ClerkProvider >
  );
}
