import type { Metadata } from "next";
import { Poppins, Henny_Penny, Lilita_One } from "next/font/google";
import Providers from "./provider/Providers";
import Navbar from "@/components/navbar";
import "./globals.css";
import { cn } from "@/lib/utils";

const poppins = Poppins({
  weight: ['400', '700'],
  variable: "--font-poppins",
  subsets: ["latin"],
});

const liltaOne = Lilita_One({
  weight: ["400"],
  variable: "--font-lilita-one",
  subsets: ["latin"],
});

const hennyPenny = Henny_Penny({
  weight: ["400"],
  variable: "--font-Henny-Penny",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn(`antialiased`, poppins.className, hennyPenny.className, liltaOne.className)}>
      <body>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
